### ISSUE TITLE
Some python error stack trace when tried to use it.

### ISSUE THREAD

**Issue by adrianjez** [Dancovich/libgdx_blender_g3d_exporter#8] opened 2016-08-28 16:27 UTC
![blender user preferences_004](https://cloud.githubusercontent.com/assets/6289000/18035021/a719b92a-6d4c-11e6-9911-9b0f38c3dd09.png)
I would like to use your addon, but I cannot do it. I am using Blender 2.77 and Manjaro linux. 
I placed folder in addons folder. Is it enough?

**Comment by Dancovich** [comment] 2016-08-28 16:36
You placed it in the right folder. It seems there is an import error in the JSON exporting script I use. I'll do some testing in Blender 2.77 and report back. Thanks for the report.

**Comment by Dancovich** [comment] 2016-10-14 16:02
Sorry for taking so long to respond. I tested this on Blender 2.77 and 2.78 in Ubuntu Linux 16.04 and this error didn't occur.

The import error (cannot import name 'FLOAT_REPR') is being given to a Python library, this constant should be present on the "json" module which is part of Python.

I don't know why your combination of Blender and Manjaro Linux is giving this error, as far as I know Blender searches for it's own bundled Python library before using the system library but your error might be coming from Blender using Manjaro's Python and not finding this particular constant declared in the json module.

If you're still having this issue (or even using my library at all) in Blender 2.78 try making sure you're using the bundled Python in Blender.

**Comment by thbell** [comment] 2016-10-27 02:40
I am having the same problem in Blender 2.76 on Ubuntu 16.04:
![image](https://cloud.githubusercontent.com/assets/1663913/19750543/97d81710-9bb7-11e6-9cfc-8a27f381018b.png)

### Problem Source
It looks like 'FLOAT_REPR' was removed from json.encoder in the transition from Python 3.5.1 to 3.5.2, according to the following diff:
https://fossies.org/diffs/Python/3.5.1_vs_3.5.2/Lib/json/encoder.py-diff.html

Blender 2.76 seems to default to Python 3.5.2 built-in, which is probably why some of us are getting this issue.

### Temporary Solution (not really reccomended)
I was able to get around the issue by opening the Python console in Blender (Shift + F4), and manually setting the 'FLOAT_REPR' value by entering the following in the console:
`import json`
`json.encoder.FLOAT_REPR = float.__repr__`

I was then able to enable and use the g3d exporter plugin in the user preferences without any error.  However, the steps in this method need to be repeated every time you restart Blender.

### Permanent Solution
I was able to fix this permanently by modifying **g3dj_json_encoder.py** in the main io_scene_g3d plugin directory.

The problem is the following line in that file does not work in Python 3.5.2 (around line 20):
`from json.encoder import encode_basestring_ascii, encode_basestring, FLOAT_REPR, INFINITY`

So I just changed it to the following:
`from json.encoder import encode_basestring_ascii, encode_basestring, INFINITY`

Also, I needed to change the FLOAT_REPR usage (around line 63):
from
`_repr=FLOAT_REPR`

to 
`_repr=float.__repr__`

I then saved the file, restarted Blender, and the export plugin worked as intended.  I have not tested this with Python 2.7, but I have confirmed that it works with Python 3.5.2.  I will submit a pull request once I verify that it works with Python 2.7.

**Comment by Dancovich** [comment] 2016-10-27 03:29
I'll just do some final testing but it seems you where on point on the cause. I'll accept the pull request after this final test.

Thanks for contributing.

**Comment by SolarLune** [comment] 2017-01-27 16:57
Hello! I'm looking into using this exporter, but I stumbled on this same bug. Is the PR being held up for some reason?

**Comment by Dancovich** [comment] 2017-01-27 17:07
@SolarLune, I swear I though it was already merged as it was already tested.

Done now, it should work. Please report if it's still giving an error.

**Closed** 2017-01-27 18:43 UTC
Labels: bug

**Comment by SolarLune** [comment] 2017-01-28 03:26
Hey, that solved it. Thanks!
